// src/engine/outline.ts
// Runtime view of the document structure parsed from data/source-outline.md
// (generated by scripts/outline.ts into src/data/outline.json).
// Single source of truth for mapping printed pages to chapter/annex labels.
import type { RankedResult } from './types';
import OUTLINE_JSON from '../data/outline.json';

export interface OutlineEntry {
  id: string;
  kind: 'chapter' | 'section' | 'annex' | 'glossary' | 'theme' | 'references';
  number: number;
  title: string;
  printedStart: number;
  printedEnd: number;
  parentId: string | null;
}

export const OUTLINE = OUTLINE_JSON as unknown as OutlineEntry[];

/** Group label for a printed page according to the outline ranges, or null. */
export function groupForPrintedPage(printedPage: number): string | null {
  if (printedPage < 1) return null;
  for (const e of OUTLINE) {
    // Only top-level structures label filter groups; sections and themes are
    // finer-grained metadata used by the Phase B chunker.
    if (e.kind === 'section' || e.kind === 'theme') continue;
    if (printedPage >= e.printedStart && printedPage <= e.printedEnd) {
      if (e.kind === 'chapter')    return `Chapter ${e.number}`;
      if (e.kind === 'annex')      return `Annex ${e.number}`;
      if (e.kind === 'glossary')   return 'Glossary';
      return 'References';
    }
  }
  return null;
}

/**
 * Map a document chunk to a coarse chapter/annex group label for filter pills.
 * Priority: explicit "CHAPTER N"/"ANNEX N" in the section title → glossary →
 * printed-page lookup from the outline (A1: replaces hard-coded page ranges).
 */
export function deriveGroup(sectionTitle: string, printedPage: number): string {
  const cm = sectionTitle.match(/\bCHAPTER\s+(\d+)/i);
  if (cm) return `Chapter ${cm[1]}`;
  const am = sectionTitle.match(/\bANNEX\s+(\d+)/i);
  if (am) return `Annex ${am[1]}`;
  if (/\bGLOSSARY\b/i.test(sectionTitle)) return 'Glossary';

  const g = groupForPrintedPage(printedPage);
  if (g) return g;

  // Printed page ≤ 0 is front matter (excluded by the chunker since A1);
  // anything else unmapped is body content without an outline entry.
  return printedPage < 1 ? 'Front matter' : 'Other';
}

/** Return unique group labels in order of first appearance across results. */
export function deriveResultGroups(results: RankedResult[]): string[] {
  const seen = new Set<string>();
  const ordered: string[] = [];
  for (const r of results) {
    const g = deriveGroup(r.chunk.sectionTitle, r.chunk.printedPage);
    if (!seen.has(g)) { seen.add(g); ordered.push(g); }
  }
  return ordered;
}
