// C1: assemble tests/fixtures/gold.json. Expected pages are computed from the PDF, never typed.
import fs from 'node:fs';
import path from 'node:path';
import { readCsvRecords } from '../lib/csv';
import { extractPdfLines } from '../lib/pdf-lines';
import { findStartPages, loadSourceText } from '../lib/source-text';
import { stripPageFurniture } from '../lib/strip-furniture';
import { NEW_QUESTIONS, REWORDED, SHORT_QUERIES } from './gold-data';
import { SOURCE_PDF_FILE } from '../../src/engine/source-pdf';
import { splitPages } from '../../src/engine/excerpts';

async function main(): Promise<void> {
  const root = process.cwd();
  const { records } = readCsvRecords(path.join(root, 'data', 'wca-qa.csv'));
  const source = await loadSourceText();
  const lines = stripPageFurniture(await extractPdfLines(path.join(root, 'source', SOURCE_PDF_FILE)));
  const paragraphPage = new Map<string, number>();
  for (const line of lines) {
    const para = line.text.match(/^((?:[1-9]\d*\.\d+(?:\.\d+)?))\s+[A-Z]/)?.[1];
    if (para && !paragraphPage.has(para)) paragraphPage.set(para, line.printedPage);
  }

  const items: unknown[] = [];
  // Multi-passage rows list one page per passage ("76; 78"); the first passage's page is the answer.
  REWORDED.forEach(([row, question], i) => {
    const r = records[row];
    items.push({ id: `r${String(i + 1).padStart(2, '0')}`, kind: 'reworded', question, expectedPrintedPage: splitPages(r.page_number)[0], expectedParagraphs: [], sourceQuestion: r.question });
  });

  for (const [id, question, paragraph, phrase, range] of NEW_QUESTIONS) {
    let page: number | undefined;
    if (paragraph) page = paragraphPage.get(paragraph);
    else page = findStartPages(source, phrase).find(p => !range || (p >= range[0] && p <= range[1]));
    if (page === undefined) throw new Error(`${id}: cannot locate ${paragraph ?? phrase} in the PDF`);
    if (paragraph && !findStartPages(source, phrase).some(p => Math.abs(p - page!) <= 1)) throw new Error(`${id}: phrase not near ¶${paragraph} (p. ${page})`);
    items.push({ id, kind: 'new', question, expectedPrintedPage: page, expectedParagraphs: paragraph ? [paragraph] : [], mustContain: phrase });
  }

  SHORT_QUERIES.forEach(([question, pattern], i) => {
    items.push({ id: `s${String(i + 1).padStart(2, '0')}`, kind: 'short', question, mustContain: pattern });
  });

  const out = path.join(root, 'tests', 'fixtures', 'gold.json');
  const gold = {
    description: 'C1 gold set of in-domain questions. kind=reworded: 80 curated questions reworded so the Q&A tier cannot match them verbatim (answer = the row\'s verbatim page). kind=new: 40 questions written from the PDF text with the verifying paragraph and phrase. kind=short: 20 one- or two-word domain queries (answered, and the answer must contain mustContain). Generated by scripts/dev/build-gold.ts.',
    items,
  };
  fs.writeFileSync(out, `${JSON.stringify(gold, null, 2)}\n`, 'utf-8');
  console.log(`Wrote ${items.length} gold items → ${path.relative(root, out)}`);
}

main().catch(e => { console.error(e); process.exitCode = 1; });
