// C1 source data for tests/fixtures/gold.json: reworded curated questions, new questions
// written from the PDF text, and short domain queries. Pages are computed by build-gold.ts.

/** [row index in data/wca-qa.csv, reworded question] — never an exact copy of the stored question. */
export const REWORDED: Array<[number, string]> = [
  [2, 'Which items count as additional items in the WCA 2030?'],
  [7, 'Explain the census approach that combines a census with administrative data.'],
  [12, 'What goals does the agricultural census aim to achieve under the WCA 2030?'],
  [17, 'What data collection method is advised for additional items?'],
  [22, 'What became of the 2020 theme on managerial decisions and ownership within the household?'],
  [27, 'Which policy fields benefit directly from agricultural census data?'],
  [32, 'How does a census of agriculture contribute to gender analysis?'],
  [37, 'Is the ten-yearly census enough to supply ongoing agricultural statistics?'],
  [42, 'If a country wants a statistical farm register out of the census, what must be decided early in planning?'],
  [47, 'In what way does the 50x2030 Initiative draw on agricultural censuses?'],
  [52, 'Which identification approach is proposed for matching holdings and households between the agricultural and population censuses?'],
  [57, 'Does WCA 2030 advise attaching a complete agricultural module to the population census?'],
  [62, 'How is the agricultural census connected to the economic census?'],
  [67, 'What is the notion of a household founded on?'],
  [72, 'Define plot.'],
  [77, 'What problem follows when some regions or kinds of holdings are left out of the census coverage?'],
  [82, 'Which two reference periods does the census of agriculture use?'],
  [87, 'Which topics should take priority in the content of the agricultural census?'],
  [92, 'Why is a sample-based structure survey not allowed to be called a census?'],
  [97, 'Describe the modular approach to census taking.'],
  [102, 'What is needed to link census data with administrative sources?'],
  [107, 'Under what conditions does a farm register work well as a census frame?'],
  [112, 'What does WCA 2030 say about mixing full enumeration with sampling?'],
  [117, 'Why do census accuracy assessments need to be reported?'],
  [122, 'Which safeguard does CAWI usually rely on to ensure the right holding answers?'],
  [127, 'How should a holding be identified and located according to WCA 2030?'],
  [132, 'What time is needed to establish an earth-observation based crop statistics system?'],
  [137, 'What does the decision tree say about items that change fast and have a reference period under six months?'],
  [142, 'Which irrigation item is essential in WCA 2030?'],
  [147, 'Name the essential items about work on the holding.'],
  [152, 'What sector categories are used for holdings?'],
  [157, 'How is the main purpose of production assigned when a holding both sells and consumes its output?'],
  [162, 'What is the typical way of gathering holding and parcel area data?'],
  [167, 'Under what circumstances is land not regarded as temporarily fallow?'],
  [172, 'How do you count area actually irrigated if land is irrigated and harvested two times in one year?'],
  [177, 'Why might associated temporary and permanent crop areas add up to more than the land area?'],
  [182, 'What separates rearing an animal from working as an employee looking after it?'],
  [187, 'What is determined by Item 0901?'],
  [192, 'What caution does WCA 2030 give about adding a community survey?'],
  [197, 'Is it right to take crop and livestock figures from community leaders rather than from holdings?'],
  [202, 'What does a tabulation programme mean?'],
  [207, 'What is meant by a classification variable?'],
  [212, 'What makes tabulation by sex of holder complicated?'],
  [217, 'For what two purposes is community-level data used in tables?'],
  [222, 'Which metadata standards does the WCA 2030 refer to?'],
  [227, 'Which geographic value-added products are recommended for dissemination?'],
  [232, 'In which situations should the census operation make use of social media?'],
  [237, 'What should be kept in a census data archive?'],
  [242, 'What is the reason for recording the respondent for an agricultural holding?'],
  [247, 'How does precision agriculture assist farmers?'],
  [252, 'What is the Annex 4 definition of woodland under the forestry theme?'],
  [257, 'How should own-use production workers be handled under Theme 9?'],
  [262, 'Explain what an agriculture structure survey is.'],
  [267, 'What are the primary aims of the agricultural census?'],
  [272, 'Which items and themes from earlier programmes were dropped in the WCA 2030?'],
  [277, 'Explain the statistical farm register and the census role in building it.'],
  [282, 'How does a reporting system differ from a census of agriculture?'],
  [287, 'Is it possible to run the agricultural and population censuses as one joint exercise?'],
  [292, 'Explain the fishing module in a census of agriculture.'],
  [297, 'What counts as a non-household sector holding?'],
  [302, 'How do you identify the holder if the household head is not the holder?'],
  [307, 'What are the drawbacks of using a cut-off threshold?'],
  [312, 'When should the agricultural census ideally be timed?'],
  [317, 'How is a census of agriculture carried out under the modular approach?'],
  [322, 'In what ways can registers and administrative data support an agricultural census?'],
  [327, 'Which enumeration methods can be used in an agricultural census?'],
  [332, 'What is the total count of essential items in WCA 2030?'],
  [337, 'Which themes contain only additional items?'],
  [342, 'What is the purpose of collecting the sex of the agricultural holder?'],
  [347, 'How do land use and land cover differ?'],
  [352, 'Define land tenure and list the tenure types WCA 2030 recognises.'],
  [357, 'How should the area of mixed and intercropped crops be measured?'],
  [362, 'How does the number of animals differ from the number of female breeding animals?'],
  [367, 'Do Themes 7 and 8 include any essential items?'],
  [372, 'How does WCA 2030 define aquaculture?'],
  [377, 'What is the reason for collecting community-level information in the census?'],
  [382, 'Through which channels should census results be disseminated?'],
  [387, 'Which ISIC categories fall within the scope of the census of agriculture?'],
  [392, 'What reference age is recommended for the agricultural holder?'],
  [397, 'Which frames are suitable for the household sector in an agricultural census?'],
];

/** New questions: [id, question, paragraph or null, phrase that must occur on the answer page, optional page range for the phrase]. */
export const NEW_QUESTIONS: Array<[string, string, string | null, string, [number, number]?]> = [
  ['n01', 'A household leases land to grow crops in a season other than the census season. Does it still count as an agricultural holding?', '4.17', 'should still be considered an agricultural holding'],
  ['n02', 'How are a field and a plot related to a parcel?', '4.20', 'A field is a piece of land within a parcel'],
  ['n03', 'What is the alternative to setting a minimum size limit for holdings?', '4.35', 'An alternative to setting minimum size limits'],
  ['n04', 'What should the census reference day be when the day of enumeration is used?', '4.38', 'mid-point of the main enumeration period'],
  ['n05', 'Why conduct the agricultural census soon after the population and housing census?', '4.41', 'agriculture-related data and field materials will still be current'],
  ['n06', 'What are the two types of agricultural holdings?', '4.5', 'holdings in the non-household sector'],
  ['n07', 'What is the classical approach to the census?', '5.6', 'conducted as a single, one-off operation'],
  ['n08', 'In the modular approach, which part is collected on a complete enumeration basis and which by sampling?', '5.12', 'core module is carried out on a complete enumeration basis'],
  ['n09', 'What conditions make a farm register a good frame for the census?', '5.24', 'regularly updated to remove units that cease to operate'],
  ['n10', 'How can the population census provide a frame without a maintained farm register?', '5.27', 'one-time exercise, without being maintained as a farm register'],
  ['n11', 'What are the disadvantages of pen and paper interviewing?', '5.45', 'complex logistics'],
  ['n12', 'How can drones be used in a census?', '5.51', 'Drones are emerging as a valuable tool'],
  ['n13', 'How are pixels used with earth observation data for crop statistics?', '5.63', 'generate a regular grid'],
  ['n14', 'What does the plus sign mean in the lists of items?', '6.7', 'All new items in the lists are marked with a'],
  ['n15', 'Why does the WCA 2030 propose community-level items?', '6.16', 'decentralised planning'],
  ['n16', 'Can both essential and additional items be used to create frames for supplementary modules?', '6.4', 'may be used to create frames for sample-based census supplementary modules'],
  ['n17', 'Which concept of household size is recommended, persons present or usual residents?', '7.1.17', 'de jure concept'],
  ['n18', 'How long is the cycle that separates temporary from permanent meadows and pastures?', '7.2.21', 'A period of less than five years is used to differentiate'],
  ['n19', 'How are agroforestry systems treated in forest and other wooded land?', '7.2.33', 'Taungya'],
  ['n20', 'How is common land used by several holdings allocated?', '7.2.45', 'common land is used by several holdings'],
  ['n21', 'Do items 0301 to 0308 ask whether holdings are equipped for irrigation?', '7.3.4', 'actual use of irrigation, not whether the holding is equipped'],
  ['n22', 'What is excluded from the area harvested?', '7.4.4', 'Area where harvest was lost because of drought'],
  ['n23', 'How is the area assigned to crops in an inter-planted plot?', '7.4.10', 'one crop is planted between rows of another crop'],
  ['n24', 'What are the three forms of animal manure?', '7.4.28', 'solid or farmyard, liquid and slurry'],
  ['n25', 'What are plant growth regulators?', '7.6.3', 'Plant growth regulators are natural or synthetic substances'],
  ['n26', 'Should the immigrant status of workers be collected for Item 0903?', '7.9.19', 'immigrant workers may significantly contribute'],
  ['n27', 'Which factors should be considered when choosing the unit for a community survey?', '8.9', 'the unit chosen for the community survey should consider operational factors'],
  ['n28', 'How does the organisation of holding fieldwork shape community data collection?', '8.12', 'depends on how fieldwork for holding-level data is organized'],
  ['n29', 'What role can community officials play in the holding survey?', '8.14', 'Community officials are sometimes engaged to help locate each household'],
  ['n30', 'Why is the area of holding a useful classification variable, and what are its limits?', '9.15', 'most widely used classification variable in agricultural census tables'],
  ['n31', 'Why is household size used as a classification variable?', '9.19', 'relationship between rural populations and land dependence'],
  ['n32', 'What is the age of the holder classification variable meant for?', '9.23', 'comparing the age demographics of farmers'],
  ['n33', 'Will the main census report contain many cross-tabulations?', '9.31', 'the number of additional cross-tabulations for the main census report will be limited'],
  ['n34', 'How can cross-tabulating community-level and holding-level data help check quality?', '9.35', 'important for assessing the quality and reliability'],
  ['n35', 'Which types of soilless farming does Annex 4 distinguish for protected-cover crops?', null, 'Hydroponic covers a range of methods used to grow agricultural crops without using soil'],
  ['n36', 'Which marital status categories are recommended for household members?', null, 'marital status categories should be based on international standards'],
  ['n37', 'How is organic agriculture defined in Annex 4?', null, 'Organic agriculture is a holistic production management system'],
  ['n38', 'Which classification of fishing gear is recommended for Item 1207?', null, 'International Standard Statistical Classification of Fishing Gears'],
  ['n39', 'In the crop classification, which crops are listed as temporary fibre crops?', null, 'Temporary fibre crops', [174, 181]],
  ['n40', 'What is the botanical name of sisal in the alphabetical list of crops?', null, 'Sisal Agave sisalana', [181, 189]],
];

/** Short domain queries (C0.2): [query, regex the answer chunk must contain]. */
export const SHORT_QUERIES: Array<[string, string]> = [
  ['fallow', 'fallow'], ['aquaculture', 'aquaculture'], ['land tenure', 'tenure'],
  ['reference period livestock', 'reference period'], ['irrigation methods', 'irrigat'],
  ['holder', 'holder'], ['sex of holder', 'sex of'], ['machinery ownership', 'machinery'],
  ['crop residue', 'residue'], ['intercropping', 'intercropp|inter-planted'],
  ['modular approach', 'modular approach'], ['community-level data', 'community-level'],
  ['tabulation', 'tabulation'], ['census frame', 'frame'], ['threshold for small holdings', 'threshold|minimum size'],
  ['cut-off threshold', 'cut-off|threshold'], ['farm register', 'farm register'],
  ['permanent crops', 'permanent crops'], ['tillage practices', 'tillage'], ['household size', 'household size'],
];
